### ISSUE TITLE
Update/upkeep read-me.

### ISSUE THREAD

**Issue by SomeSN** [SomeSN/url-shortener#11]
The read me needs to be updated with useful information like branch super types we are using and other things that might be pertinent.

I'd like to do that, but if someone else would like to do that, that's great.

I was going to use the branch super types Ricky suggested.

Feature, bug-fix, chore, refactor. I think I missed one, so if someone could tell me what it is, that would be greatly appreciated. Or if anyone has any other suggestions, that's also great.

I also wanted to add Core. It's like feature, except it's something that is relevant to the program as a whole, like the file structure or the read me rather than a specific functionality. It'll be rarely used, but I think it's a good thing to have.

**Comment by vanwars** [comment]
This is a good idea, but lower priority. Once Parts 1-3 are completed, feel free to do this.

**Comment by SomeSN** [comment]
At this point, this isn't going to be done I don't think, so I'm closing this issue. Someone can submit it again if it somehow becomes relevant,
