### ISSUE TITLE
Refactoring code.

### ISSUE THREAD

**Issue by SomeSN** [SomeSN/url-shortener#12]
I like refactoring code to make it more readable, so I'd love to do that if no one minds. Unless someone wanted me to do more functional refactoring like cleaning up efficiency or reordering things to make it more clear what's going on, I'd be doing things like making sure the indentation and white space is consistent between all our code.

Anyone else can do this too, but I actually enjoy it! And I think it makes sense for one person to be in charge of this so we have a single format for our final code. But if anyone disagrees, I'd love to discuss your opinions on the matter.

In general here is how I refactor code:

I make sure that I indent all children, and I try to put open braces and parentheses on the same line as the block initialization, while the closing braces and parentheses are on their own lines at the same level as the opening block. For example:

const aFunction = () => {
     //Logic here.
}

I also tend to use one line of white space between each function, but I don't like too much white space, because I feel it's distracting.

If someone wants different formatting or to just leave our code as it is, that's something we should decide as a group. Hope to hear what you think!

**Comment by vanwars** [comment]
Let's leave the refactoring 'til the end. Let's prioritize small, modular tasks first and come back to this. Code style standards are something that the groups should collaboratively develop. Let's table this for next week and put it as a group discussion point.

**Comment by SomeSN** [comment]
This issue is basically irrelevant now, so I'm closing it.
