### ISSUE TITLE
Client: send request to server

### ISSUE THREAD

**Issue by vanwars** [SomeSN/url-shortener#13]
@Noi-Git @Saranrat13: 
1. Update the `client/index.html` file (and the corresponding CSS file) so that it looks how you want it to look.
2. Rename `server-interaction.js` -->  `main.js` and update the path in your index.html.
3. Delete `future-server-interaction.js`, as it is currently beyond the scope of the project. Your team can always add it back, but it shouldn't be in master yet.
4. Ensure that `main.js` successfully reads the longURL and the shortCode from the DOM and issues a POST request to the http://localhost:3000/urls/ endpoint (which hasn't been implemented yet).

> ## Important:
> 1. Before you begin, pull from master and then make a new branch from master
> 2. When you're done, make a pull request at let Ricky and I know.

**Comment by Miss-Megan** [comment]
2. I renamed server-interaction.js --> main.js and updated the path in our index.html
3. I deleted future-server-interaction.js

The changes are in Megan-Phase1-May5 (sorry for the confusing title)

**Comment by vanwars** [comment]
@Noi-Git @Saranrat13. Nice work with the HTML and CSS!

A quick comment:
Now that Megan's branch has been merged and Issue #15 has been addressed, you need to implement Part 4 of this issue: 
> Ensure that main.js successfully reads the longURL and the shortCode from the DOM and issues a POST request to the http://localhost:3000/urls/ endpoint. 

The next time you are working, begin by getting the latest (using your *awesome Git Cheatsheet). Then, fix your code so that it posts to http://localhost:3000/urls/ instead of saving to localStorage (which is a client-centered solution, and will not work for an actual app). I have merged a file called "main-working.js" into master to give you some ideas. Please take a look at it and see how it posts to the server using fetch.

Best,
Sarah

**Comment by vanwars** [comment]
Noi and Amm finished this task in Pull Request #29.
