### ISSUE TITLE
Server: create a 7-character random character generator

### ISSUE THREAD

**Issue by vanwars** [SomeSN/url-shortener#14]
@SomeSN: 
Please create a Node Module that returns a 7-character string of numbers and letters. To organize this:
1. in the `server` directory, create a new folder called `url-code`
2. inside the `url-code` folder, create an` index.js` file
3. implement the logic here, and be sure to conform to the node module syntax.

> ## Important:
> 1. Before you begin, pull from master and then make a new branch from master
> 2. When you're done, make a pull request at let Ricky and I know.

**Comment by vanwars** [comment]
PR #23 successfully addresses this Issue.

**Comment by SomeSN** [comment]
Since the random character generator is up and working, I'm going to close this issue at the end of the day unless someone has a reason for me not to.

**Comment by vanwars** [comment]
Sounds good!

**Comment by vanwars** [comment]
This was fixed in PR #28.
