### ISSUE TITLE
Server: Create a `/urls` POST route: Part 1

### ISSUE THREAD

**Issue by vanwars** [SomeSN/url-shortener#15]
@Miss-Megan 
Please create the /urls POST route inside of `server/app.js`. To do this:
* in the `server` directory, create a new folder called `routes`
* inside the `routes` folder, create an `index.js` file
* implement PART 1 of the POST logic here: read the request from the user and return a response that informs the user that the URL data was successfully 'created'. Be sure to conform to the node module syntax.

> ## Important:
> 1. Before you begin, pull from master and then make a new branch from master
> 2. When you're done, make a pull request at let Ricky and I know.

**Comment by Miss-Megan** [comment]
Having a little trouble with the Post logic, but I think its okay for now in phase 1. Maybe group members could check it out and see if it's okay?

**Comment by vanwars** [comment]
This has been merged.
