### ISSUE TITLE
Client: Display Success Message

### ISSUE THREAD

**Issue by vanwars** [SomeSN/url-shortener#18]
@Noi-Git @Saranrat13.
Once Issue #15 is complete, update the `main.js` (client-side code) so that it displays a nice success message to the DOM.

**Comment by Noi-Git** [comment]
Done

**Comment by Saranrat13** [comment]
@vanwars @ayyrickay we done.

**Comment by Saranrat13** [comment]
@vanwars @ayyrickay @Noi-Git we done!

**Comment by vanwars** [comment]
Completed in PR #29
