### ISSUE TITLE
Server: Create URLShortener Schema

### ISSUE THREAD

**Issue by vanwars** [SomeSN/url-shortener#19]
@Miss-Megan After completing Issue #15, create a Schema for your URLs MongoDB collection. To do this:
1. Create a new folder in the server directory called `models`
2. Create a `models/index.js` file.
3. Implement the schema.

**Comment by ayyrickay** [comment]
@SomeSN @Saranrat13 @Miss-Megan @Noi-Git Nice job addressing this in #32 . If you can take a second to close issues that are completed and populate new ones, it gives Sarah and I an idea of what you're doing!

**Comment by Noi-Git** [comment]
Hi Ricky,
Sorry, I have been sick. I am going to the lab today and will figure out with the group members and Sarah if there anything we have to do to finish the project.
Thank you,
Noi
