### ISSUE TITLE
Server - Random String Generation Module

### ISSUE THREAD

**Issue by SomeSN** [SomeSN/url-shortener#21]
The random string generation module is up in its own branch. It worked before I made it a module, so it should work now, but a second set of eyes would be appreciated since I'm not entirely sure I am using module.exports correctly.

EDIT: Re-pushed a version of the module that is require-able and seems to work and an app that tests it. If anyone wants to try and break the code, that would be awesome, but I'm pretty sure it's ready to be used.

**Comment by Miss-Megan** [comment]
Thank you TK. Just a thought, but maybe we could only the random character generator, opposed to the randomNumberGenerator, randomStringGenerator and the randomCharGenerator.

**Comment by SomeSN** [comment]
The randomStringGenerator uses the randomCharGenerator which uses the randomNumber generator. And currently the randomStringGenerator generates what we need (a random String of 7 characters), so all we need to do is require it in the app and then call it where we need it. Assuming it still works right after being converted to a module.

I intentionally made it stand alone so we wouldn't have to integrate a lot of code into the app. All we'll need to do is check whether or not the string we get from the client is empty, and if it is, call the appropriate random string generating function.

**Comment by SomeSN** [comment]
There is a pull request with a simplified, require-able function. So, unless anyone has anything more to say here, I'm going to close this issue before I go to bed tonight.
