### ISSUE TITLE
About meeting tomorrow...

### ISSUE THREAD

**Issue by SomeSN** [SomeSN/url-shortener#27]
I'm checking in to see if you still want to meet tomorrow, or indeed, meet at lab, or if you guys think that communicating through git hub is enough.

**Comment by Miss-Megan** [comment]
@SomeSN @Noi-Git @Saranrat13 

Personally, I feel my time is better spent staying home and working independently tonight. The task assignments and Github communication seem to be going well :) But if y'all want to meet, I'm game.  I will also be at lab tomorrow night, so if anyone wants to meet before/after lab, that also works for me. Thoughts?

**Comment by SomeSN** [comment]
That's fine with me! Hopefully Noi will see this. I talked to Amm via text and she had the same thought as you. If we don't hear from Noi, I'll go out to meet her just so she doesn't think we forgot about her. I can show up tomorrow if you need me to. Text me if you do.

**Comment by Noi-Git** [comment]
Sorry guys, I totally forgot

Noi

**Comment by vanwars** [comment]
Closing this: expired.
