### ISSUE TITLE
Task Assignment

### ISSUE THREAD

**Issue by Miss-Megan** [SomeSN/url-shortener#7]
TK: 
1. Refactor your code 

Add a gitignore and update your file structure. You should have a client directory, and a server directory. The client directory should include an index.html and an assets directory, and your server directory should include an app.js file and a routes directory.

Update the README.md to inform people of your git branching model, as well as a Getting Started guide that informs people to install node modules, etc.

Noi: 
2. Finish the Client <> Server Interaction

Return the shortened string, and find an appropriate data structure for storing it (or the provided shortened URL) in local memory. DO NOT USE A DATABASE.

Megan:
3. Establish application logic

If there is no shortened string included in the request, generate a random string of 6 characters to be the shortened URL.

Amm (with support of whole group):
4. Begin implementing reroute logic

Write an endpoint that can receive the shortened tag and redirect to a long URL. For initial testing, you can focus on just creating any route that can redirect to a URL of your determination (e.g., a shortened URL that goes to http://google.com ) (Links to an external site.)Links to an external site.

**Comment by vanwars** [comment]
I'm going to close this Issue and assign the tasks therein to individuals.
